### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Brillyz** [chickendrop89/magisk-nik-gapps#4]
I don't know if I'm doing something wrong as to why is this happening, but I get 2 different errors when trying to run (main.py -i pathto.zip -o output) in python on windows, I have the latest version of python with everything installed mentioned in the instructions.

First is a syntax error, it gives this: 

File Path\main.py", line 159
    MODULE_VERSION_CODE = f"{version_regex.replace("-", "")}"
                                                    ^
SyntaxError: f-string: unmatched '('

Now if I change line 159 from: 
MODULE_VERSION_CODE = f"{version_regex.replace("-", "")}" 
to 
MODULE_VERSION_CODE = f'{version_regex.replace("-", "")}'

That error disappears

The 2nd error after changing line 159 will appear after it extracted all the zip files, it gives this:

Traceback (most recent call last):
  File "Path\main.py", line 344, in <module>
    resolveGappsDirectories()
  File "Path\main.py", line 240, in resolveGappsDirectories
    if src_file.split("/", 2)[2] in os.listdir(dst_file):
       ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

Now if I change line 240 from: 
if src_file.split("/", 2)[2] in os.listdir(dst_file):
                __fixDirectories()
to 
split_src = src_file.split("/", 2)
            if len(split_src) > 2 and split_src[2] in os.listdir(dst_file):
                __fixDirectories()

This error also disappears, and it'll extract everything and build the final zip file, I flashed the zip file through ksu as well and everything was fine, now I don't know if the error is on my side or something else.

**Comment by chickendrop89** [comment]
I can not reproduce the first error

**Comment by chkndrp** [comment]
I could not reproduce the first error even on my windows machine, but i see what's wrong
